import { screens } from '../data/customerData'

export const screenPaths = {
  [screens.login]: '/login',
  [screens.signup]: '/signup',
  [screens.userType]: '/signup/type',
  [screens.terms]: '/signup/terms',
  [screens.category]: '/signup/category',
  [screens.bizReg]: '/signup/biz-reg',
  [screens.companyInfo]: '/signup/company-info',
  [screens.phone]: '/signup/phone',
  [screens.address]: '/signup/address',
  [screens.region]: '/signup/region',
  [screens.welcome]: '/signup/welcome',
  [screens.home]: '/customer/home',
  [screens.estimateHome]: '/customer/estimate',
  [screens.estimateStart]: '/customer/estimate/start',
  [screens.estimateLoading]: '/customer/estimate/loading',
  [screens.estimateDone]: '/customer/estimate/done',
  [screens.estimateOutput]: '/customer/estimate/output',
  [screens.myEstimateList]: '/customer/mypage/estimates',
  [screens.matchingHome]: '/customer/matching',
  [screens.matchingEstimateSelect]: '/customer/matching/estimate',
  [screens.matchingAddressList]: '/customer/matching/address-list',
  [screens.matchingAddressSelect]: '/customer/matching/address',
  [screens.matchingSchedule]: '/customer/matching/schedule',
  [screens.matchingProgress]: '/customer/matching/progress',
  [screens.matchingAuction]: '/customer/matching/auction',
  [screens.matchingPartner]: '/customer/matching/partner',
  [screens.matchingPartnerInfo]: '/customer/matching/partner-info',
  [screens.matchingDone]: '/customer/matching/done',
  [screens.riskHome]: '/customer/risk',
  [screens.riskSelect]: '/customer/risk/select',
  [screens.riskLoading]: '/customer/risk/loading',
  [screens.riskDone]: '/customer/risk/done',
  [screens.riskOutput]: '/customer/risk/output',
  [screens.myRiskList]: '/customer/mypage/risks',
  [screens.chatList]: '/customer/chat',
  [screens.chatRoom]: '/customer/chat/room',
  [screens.mypage]: '/customer/mypage',
  [screens.myReviews]: '/customer/mypage/reviews',
  [screens.profile]: '/customer/mypage/profile',
  [screens.matchHistory]: '/customer/mypage/matching-history',
  [screens.reviewWrite]: '/customer/mypage/review-write',
}

export const routeScreens = Object.entries(screenPaths).map(([screen, path]) => ({ screen, path }))
